import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin,AiFillGithub,AiFillInstagram, AiFillFacebook} from 'react-icons/ai'
import Myself from '../public/Myself.webp'
import Contact from '@/components/contact'
import Project from '@/components/Project'
import { useState,useEffect } from 'react'
import Image from 'next/image'


export default function Home({services,projectos}) {
  const [darkMode, setDarkMode] = useState(true);
  const [shadow, setShadow] = useState("");
 
  useEffect(() => {

    

    const handleBg = () => {
 

      if (window.scrollY >= 80) {
        setShadow("shadow-lg");
         
      } else {
        setShadow("");
      
      }
    };

    window.addEventListener('scroll', handleBg);

  }, []);

   return (
    <div className={darkMode ? "dark" : ""}>
    <Head>
      <title>My Portfolio</title>
      <meta name="description" content="Generated by "/>
      <link rel="icon" type="" href="/"/>
    </Head>

    <main className={darkMode==false ?`bg-white px-10`:`bg-gray-900 text-white px-10`} >
    
      <section className='min-h-screen'> 

         <nav className={darkMode==false?` fixed ${shadow} bg-white left-0 top-0 z-10 w-full py-4 md:py-8 px-4  md:px-8 flex justify-between`:` py-4 md:py-8 ${shadow} bg-gray-900 px-4 fixed left-0 top-0 z-10 w-full text-white md:px-8 flex justify-between`
        
        }>
          <div> 
          <h1 className='text-2xl cursor-pointer font-burtons'>RicardoPS</h1>
          </div>
          <ul className='flex gap-8 items-center'>
            <li className='ease-in hover:scale-105 duration-200'>
              <a className='py-2 px-4 text-center text-white rounded-md bg-gradient-to-r from-cyan-500 to-teal-500' href='#contactos'>Contacte</a>
            </li>
            <li onClick={() => {  
              setDarkMode(!darkMode);
 
               
              }} className='cursor-pointer ease-in hover:scale-105 duration-200'>
              <BsFillMoonStarsFill
                 />
                 
            </li>
          </ul>
        </nav>
         <div className='flex flex-col pt-40 items-center'>
          <h2 className='text-5xl md:text-7xl py-2 md:font-burtons text-teal-500  text-center'>Ricardo Pilartes</h2>
          <h3 className='py-2 md:text-xl md:font-montserrat text-2xl '>Programador e Web Designer</h3>
          <p className="text-md text-center md:font-montserrat max-w-[80vw] md:max-w-[50vw] py-2 leading-8">
          Desde o início da minha jornada como designer freelancer e desenvolvedor, eu fiz trabalho remoto para
              <span className="text-teal-500"> Agências </span>
              e <span className="text-teal-500">startups </span>
              e colaborei com pessoas talentosas para criar produtos digitais
              tanto para uso de empresas como dos consumidores.
            </p>
        </div>
        <div className={darkMode==false?`flex py-2 pb-8  text-5xl text-gray-600 justify-center gap-8 md:gap-16`:
      `flex py-2 pb-8  text-5xl text-gray-600 justify-center gap-8 md:gap-16`
      }>
            <a href='https://github.com/RicardoP24' rel="noreferrer"  target='_blank' className={darkMode==false?`hover:text-black cursor-pointer`:
          `hover:text-white cursor-pointer`
          }> <AiFillGithub  /></a>

            <a href='https://www.linkedin.com/in/ricardo-pilartes-da-silva-54243b221/' rel="noreferrer"  target='_blank' className={darkMode==false?`hover:text-black cursor-pointer`:
          `hover:text-white cursor-pointer`}>  <AiFillLinkedin/></a>


            <a href='https://www.facebook.com/profile.php?id=100015332328463' rel="noreferrer" target='_blank' className={darkMode==false?`hover:text-black cursor-pointer`:
          `hover:text-white cursor-pointer`}> <AiFillFacebook /></a>

            <a href='https://www.instagram.com/rp_designcriativo/' target='_blank' rel="noreferrer"  className={darkMode==false?`hover:text-black cursor-pointer`:
          `hover:text-white cursor-pointer`}> <AiFillInstagram/></a>

        </div>

        <div className='relative mx-auto text-center overflow-hidden  bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 pb-16'>
                <Image
                  className='bg-cover '
                  src={Myself}
                  alt='/'
                />
         </div>
      </section>
      
      <section className='mt-16   md:px-16 '>

          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Os meus Serviços</h3>
            <p className="text-md py-2 leading-8">
            Desde o início da minha jornada como designer freelancer e desenvolvedor, eu fiz trabalho remoto para
              <span className="text-teal-500"> Agências </span>
              e <span className="text-teal-500">startups </span>
              e colaborei com pessoas talentosas para criar produtos digitais
              tanto para uso de empresas como dos consumidores.
            </p>
            <p className="text-md py-2 leading-8 ">
            Eu ofereço a partir de uma ampla gama de serviços, incluindo design de marca,
              programação e ensino.
            </p>
          </div>

          <div className="lg:flex gap-10">
            {
              services.map((val)=>
                <div key={val.title} className={darkMode==false?
                  `text-center hover:text-white hover:bg-teal-500 hover:scale-105 ease-in duration-200  shadow-lg p-10 rounded-xl my-10  flex-1`
                :`text-center hover:text-white hover:bg-teal-500 hover:scale-105 ease-in duration-200 shadow-white shadow-lg p-10 rounded-xl my-10  flex-1`}>
                {/*<Image src={design} width={100} height={100} />*/}
                <h3 className="text-lg font-bold pt-8 pb-2  ">
                  {val.title} 
                </h3>
                <p className="py-2">
                 {val.Description}
                </p>
                <h4 className="py-4 font-bold">Ferramentas</h4>
                {
                  val.tools.map(tool=>
                    <p key={tool} className=" py-1">{tool}</p>
                  )
                }
 
              </div>
              )
            }
        
        
          </div>

      </section>
     
      <section   className='md:px-8'>
        <Project data={projectos}/>
      </section>

      <section id='contactos' className='md:px-8'>
        <Contact/>
      </section>

    </main>
      
    </div>
  )
}
export async function getServerSideProps(){

  const data = await import('../data/data.json');
  console.log(data.projectos);
  
  return { 
    props:{ 
      services:data.Services,
      projectos:data.projectos
    }
  };

}